/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and readiness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current door state, hold-open, sensor and relay health */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/door/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open the door (idempotent, single-flight, verified)
         * @description No pulse is sent if the door is already OPEN. While the door is moving a second command is rejected with 409
         *     (`POST /v1/door/stop` is the exception). With `wait=true` (default) the response is returned after
         *     `door.travelSeconds` with the verified outcome; `ok=false` and `to=STUCK` when the sensor did not confirm.
         *
         *     From `STOPPED` the opener reverses the travel that was interrupted, so only the direction in `nextPress`
         *     is accepted; the other one is rejected with 409 `door_direction` rather than silently moving the door the
         *     wrong way. Verification from `STOPPED` is weak by construction: the sensor already reads `isOpened`.
         */
        post: operations["openDoor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/door/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close the door (idempotent, single-flight, verified)
         * @description Mirrors `POST /v1/door/open`. From `STOPPED` only the direction in `nextPress` is accepted; a `close`
         *     on a door that was stopped mid-close is rejected with 409 `door_direction`, because one press would
         *     open it. Automatic closes (nightly check, LPR) skip a `STOPPED` door entirely and notify instead.
         */
        post: operations["closeDoor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/door/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pulse the relay once regardless of state (not for widgets or Siri) */
        post: operations["toggleDoor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/door/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop the door part-way (one press while it is travelling)
         * @description Sends the same single relay press the wall button does. While the door is travelling an opener stops
         *     it, leaving the door part-way; this is the only command allowed during travel, and it cancels the
         *     `open`/`close` that was counting down (that command's `CommandResult` returns with `error=cancelled`).
         *
         *     The result is **never verified**: the tilt sensor reports `isOpened` for anything that is not fully
         *     closed, so the bridge cannot confirm where the door came to rest. The response carries
         *     `pulsed=true, verified=false, to=STOPPED`.
         *
         *     409 `door_not_moving` when the door is not travelling — there is nothing to stop, and a press would
         *     move the door instead.
         */
        post: operations["stopDoor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auto-actions/{id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse an automatic action (LPR auto-open/close) within its undo window
         * @description Auto-actions carry an `autoActionId` in their `Alert` and `auto-action` events. Undo issues the reverse
         *     command (`close` after an auto-open, `open` after an auto-close) and waits for verification. After the
         *     undo window (60 s by default) the action is no longer undoable and the route answers 404 `undo_expired`.
         */
        post: operations["undoAutoAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hold the door open (suppress alerts) for N minutes */
        post: operations["setHold"];
        /** Clear the hold-open flag */
        delete: operations["clearHold"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent events stream
         * @description `text/event-stream`. Event names: `state`, `command`, `alert`, `hold`, `vehicle`, `heartbeat`.
         *     Each `data:` line is the JSON of the matching schema (`State`, `CommandResult`, `Alert`, `Hold`, `VehiclePresence`).
         *     A `state` event is sent immediately on connect. Bearer token may be passed as `?token=` for EventSource clients.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Command and alert audit log, newest first */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The same log as a CSV download (spreadsheet export, curl-friendly) */
        get: operations["exportAuditCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Relays, sensors and cameras seen on the console plus the suggested/current door mapping */
        get: operations["getDiscovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/alarm-manager/{secret}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Per-install secret (`WEBHOOK_SECRET`). Wrong secret → 404, never 401, to avoid enumeration. */
                secret: string;
            };
            cookie?: never;
        };
        /** UniFi Protect Alarm Manager webhook target (GET variant) */
        get: operations["alarmManagerWebhookGet"];
        put?: never;
        /** UniFi Protect Alarm Manager webhook target (POST) */
        post: operations["alarmManagerWebhookPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a one-time invite code for another phone (admin token only)
         * @description The code is valid for 15 minutes and can be claimed once. `joinUrl` is a `garageopener://join` link carrying the
         *     bridge address (`b`), the code (`c`), the expiry as unix seconds (`e`) and, when given, the suggested member
         *     name (`n`); show it as a QR or share it. Member tokens cannot create invites.
         */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{code}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem an invite code for a named member token (no auth) */
        post: operations["claimInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phones that hold a member token */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a member token (admin token only; a member may revoke itself) */
        delete: operations["revokeMember"];
        options?: never;
        head?: never;
        /** Rename a member (admin token renames anyone; a member may rename itself) */
        patch: operations["renameMember"];
        trace?: never;
    };
    "/v1/mock/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Drive the in-memory Protect simulator (BRIDGE_MODE=mock only)
         * @description State is keyed by bearer token so concurrent reviewers never collide; it expires after 60 min idle.
         */
        post: operations["mockAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description `STOPPED` means a press interrupted travel and the door is resting part-way. The garage-mounted
         *     sensor is a single tilt contact, so the bridge cannot measure how far: `STOPPED` is remembered,
         *     not observed, and degrades to `OPEN` after a restart or a stop made at the wall button.
         * @enum {string}
         */
        DoorState: "CLOSED" | "OPENING" | "OPEN" | "CLOSING" | "UNKNOWN" | "STUCK" | "STOPPED";
        Error: {
            /** @description Machine code (e.g. `unauthorized`, `door_busy`, `door_not_moving`, `door_direction`, `protect_unavailable`, `validation`) */
            error: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Health: {
            /** @description false until the instance is ready (live mode startup may retry in the background) */
            ok: boolean;
            /** @description Instance started (console discovered or mapping configured) */
            ready?: boolean;
            /** @description Last startup failure message while not ready */
            lastError?: string;
            /** @description Operational warnings, e.g. relay_output_stuck */
            warnings?: string[];
            /** @enum {string} */
            mode: "live" | "mock";
            version: string;
            protect: {
                ok: boolean;
                applicationVersion?: string;
                /** Format: date-time */
                lastSuccessAt?: string;
                error?: string;
            };
        };
        Battery: {
            percentage?: number | null;
            isLow: boolean;
        };
        SensorInfo: {
            id: string;
            name: string;
            connected: boolean;
            isOpened: boolean;
            /** Format: date-time */
            openStatusChangedAt?: string;
            battery: components["schemas"]["Battery"];
            signalQuality?: number | null;
        };
        RelayInfo: {
            id: string;
            /** @description Numeric output index on the relay (0 or 1) */
            outputId: number;
            name: string;
            connected: boolean;
            /** @enum {string} */
            pulseMode: "native" | "emulated";
            /** @description Refreshed from the console on every poll and after each command */
            pulseDurationMs?: number | null;
            /** @description Pulse output has reported state on for longer than max(2 x pulseDuration, 3 s); commands are refused with error relay_output_stuck */
            outputStuck?: boolean;
        };
        Hold: {
            active: boolean;
            /** Format: date-time */
            until?: string;
            minutes?: number;
            /** Format: date-time */
            setAt?: string;
        };
        HoldRequest: {
            minutes: number;
        };
        VehiclePresence: {
            present: boolean;
            /** Format: date-time */
            since?: string;
            /** @enum {string} */
            source?: "camera-heuristic" | "mock";
            /** @description Heuristic from interior camera vehicle detections until LPR */
            note?: string;
        };
        State: {
            door: components["schemas"]["DoorState"];
            /** @description Raw sensor contact */
            isOpened: boolean;
            /**
             * Format: date-time
             * @description When the current `door` state started
             */
            since: string;
            /**
             * Format: date-time
             * @description Last sensor contact change
             */
            lastChangedAt?: string;
            hold: components["schemas"]["Hold"];
            sensor: components["schemas"]["SensorInfo"];
            relay: components["schemas"]["RelayInfo"];
            vehicle?: components["schemas"]["VehiclePresence"];
            /** @enum {string} */
            mode: "live" | "mock";
            /** @description Console reachable at last poll */
            connectionOk: boolean;
            /** Format: date-time */
            updatedAt: string;
            openTooLongMinutes?: number;
            travelSeconds?: number;
            /**
             * @description What one relay press does right now. The relay emulates a wall button, so the opener's own
             *     reversal logic decides: moving → `stop`, `STOPPED` → the reverse of the interrupted travel,
             *     otherwise the opposite of the resting state. Absent while the door state is UNKNOWN.
             * @enum {string}
             */
            nextPress?: "open" | "close" | "stop";
        };
        CommandResult: {
            ok: boolean;
            /** @enum {string} */
            command: "open" | "close" | "toggle" | "stop";
            from: components["schemas"]["DoorState"];
            to: components["schemas"]["DoorState"];
            /** @description false when already in the target state */
            pulsed: boolean;
            verified: boolean;
            auditId: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string;
            /** @description verification_failed | relay_output_stuck | cancelled */
            error?: string;
        };
        CommandAccepted: {
            /** @constant */
            accepted: true;
            /** @enum {string} */
            command: "open" | "close" | "toggle" | "stop";
            auditId: number;
            /** Format: date-time */
            expectedBy: string;
        };
        Alert: {
            id: string;
            /** @enum {string} */
            rule: "open-too-long" | "nightly-check" | "vehicle-inside-door-open" | "vehicle-left-door-open" | "lpr-auto-open" | "lpr-auto-close";
            title: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
            actions: ("close-now" | "hold-2h" | "ignore" | "undo")[];
            /** Format: date-time */
            undoUntil?: string;
            /** @description Id for `POST /v1/auto-actions/{id}/undo` */
            autoActionId?: string;
        };
        /** @description One SSE frame; `event` is the frame name and `data` its JSON payload. */
        SseEvent: {
            /** @enum {string} */
            event: "state" | "command" | "alert" | "hold" | "vehicle" | "heartbeat";
            data: components["schemas"]["State"] | components["schemas"]["CommandResult"] | components["schemas"]["Alert"] | components["schemas"]["Hold"] | components["schemas"]["VehiclePresence"] | {
                /** Format: date-time */
                at?: string;
            };
        };
        Invite: {
            code: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description `garageopener://join?v=1&b=<bridge url>&c=<code>&e=<unix seconds>[&n=<name>]` */
            joinUrl: string;
            /** Format: uri */
            bridgeUrl?: string;
            /** @description Suggested member name, echoed from the request */
            name?: string;
        };
        InviteClaim: {
            /** @description Long-lived bearer token for this phone; shown once */
            token: string;
            member: components["schemas"]["Member"];
            bridge: {
                version: string;
                /** @enum {string} */
                mode: "live" | "mock";
                /** Format: uri */
                publicUrl?: string;
            };
            mapping?: components["schemas"]["DoorMapping"];
        };
        Member: {
            id: string;
            name: string;
            /**
             * @description admin = configured via BRIDGE_TOKENS
             * @enum {string}
             */
            kind: "admin" | "member";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** @description True for the caller's own token */
            isCurrent?: boolean;
        };
        AuditEntry: {
            id: number;
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "command" | "alert" | "hold" | "webhook" | "auto-action" | "mock" | "member";
            source: string;
            /** @description Name of the phone whose token issued the command, when known */
            member?: string;
            command?: string;
            from?: components["schemas"]["DoorState"];
            to?: components["schemas"]["DoorState"];
            /** @enum {string} */
            outcome: "ok" | "noop" | "failed" | "rejected" | "notified" | "undone" | "stopped";
            detail?: string;
        };
        Discovery: {
            relays: {
                id: string;
                name: string;
                connected?: boolean;
                outputs: {
                    id: number;
                    name?: string | null;
                    /** @description `garageDoor` when configured as Pulse */
                    type?: string | null;
                    pulseDurationMs?: number | null;
                }[];
            }[];
            sensors: {
                id: string;
                name: string;
                mountType: string;
                isOpened: boolean;
                connected?: boolean;
            }[];
            cameras: {
                id: string;
                name: string;
                smartDetectTypes?: string[];
            }[];
            suggested?: components["schemas"]["DoorMapping"];
            current: components["schemas"]["DoorMapping"];
            autoPaired: boolean;
        };
        DoorMapping: {
            relayId: string;
            outputId: number;
            sensorId: string;
            interiorCameraId?: string | null;
            drivewayCameraId?: string | null;
        };
        /** @description Best-effort shape; the bridge tolerates unknown fields and logs raw payloads at debug. */
        AlarmManagerPayload: {
            alarm?: {
                name?: string;
                triggers?: ({
                    key?: string;
                    device?: string;
                    value?: string;
                } & {
                    [key: string]: unknown;
                })[];
            } & {
                [key: string]: unknown;
            };
            timestamp?: number;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Verified outcome */
        CommandResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CommandResult"];
            };
        };
        /** @description Command accepted; follow `/v1/events` or poll `/v1/state` */
        CommandAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CommandAccepted"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Requires an admin token (one of BRIDGE_TOKENS) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Door is moving or another command is in flight (`door_busy`), the door is not moving so there is
         *     nothing to stop (`door_not_moving`), or the door is `STOPPED` and one press moves it the other way
         *     (`door_direction`).
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Console unreachable */
        ProtectUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Wait for verification (default true). `false` returns 202 immediately. */
        Wait: boolean;
        /** @description Free-text origin recorded in the audit log (e.g. `app`, `widget`, `siri`, `watch`, `shortcut`). */
        Source: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bridge is up. `protect.ok=false` means the console is unreachable (still 200). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["State"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    openDoor: {
        parameters: {
            query?: {
                /** @description Wait for verification (default true). `false` returns 202 immediately. */
                wait?: components["parameters"]["Wait"];
                /** @description Free-text origin recorded in the audit log (e.g. `app`, `widget`, `siri`, `watch`, `shortcut`). */
                source?: components["parameters"]["Source"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CommandResult"];
            202: components["responses"]["CommandAccepted"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ProtectUnavailable"];
        };
    };
    closeDoor: {
        parameters: {
            query?: {
                /** @description Wait for verification (default true). `false` returns 202 immediately. */
                wait?: components["parameters"]["Wait"];
                /** @description Free-text origin recorded in the audit log (e.g. `app`, `widget`, `siri`, `watch`, `shortcut`). */
                source?: components["parameters"]["Source"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CommandResult"];
            202: components["responses"]["CommandAccepted"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ProtectUnavailable"];
        };
    };
    toggleDoor: {
        parameters: {
            query?: {
                /** @description Wait for verification (default true). `false` returns 202 immediately. */
                wait?: components["parameters"]["Wait"];
                /** @description Free-text origin recorded in the audit log (e.g. `app`, `widget`, `siri`, `watch`, `shortcut`). */
                source?: components["parameters"]["Source"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CommandResult"];
            202: components["responses"]["CommandAccepted"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ProtectUnavailable"];
        };
    };
    stopDoor: {
        parameters: {
            query?: {
                /** @description Free-text origin recorded in the audit log (e.g. `app`, `widget`, `siri`, `watch`, `shortcut`). */
                source?: components["parameters"]["Source"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CommandResult"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ProtectUnavailable"];
        };
    };
    undoAutoAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CommandResult"];
            401: components["responses"]["Unauthorized"];
            /** @description Unknown auto-action or undo window elapsed (error undo_expired) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: components["responses"]["Conflict"];
            503: components["responses"]["ProtectUnavailable"];
        };
    };
    setHold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            /** @description Hold set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hold"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    clearHold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared (also when no hold was active) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return entries with id lower than this */
                before?: number;
                /** @description Comma-separated audit kinds to include; omit for all */
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries: components["schemas"]["AuditEntry"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    exportAuditCsv: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return entries with id lower than this */
                before?: number;
                /** @description Comma-separated audit kinds to include; omit for all */
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV with a header row: id,at,kind,source,member,command,from,to,outcome,detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discovery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ProtectUnavailable"];
        };
    };
    alarmManagerWebhookGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Per-install secret (`WEBHOOK_SECRET`). Wrong secret → 404, never 401, to avoid enumeration. */
                secret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown secret */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alarmManagerWebhookPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Per-install secret (`WEBHOOK_SECRET`). Wrong secret → 404, never 401, to avoid enumeration. */
                secret: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlarmManagerPayload"];
            };
        };
        responses: {
            /** @description Accepted and processed (thumbnails discarded) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown secret */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description Address the invitee should use (defaults to PUBLIC_URL or the request origin)
                     */
                    publicUrl?: string;
                    /** @description Who the invite is for, e.g. Margo; pre-fills the name on the joining phone */
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    claimInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Member name shown to the admin and in the audit log, e.g. Margo */
                    deviceName: string;
                };
            };
        };
        responses: {
            /** @description Claimed; the code is now consumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteClaim"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Unknown, expired or already claimed code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members: components["schemas"]["Member"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Unknown member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renameMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Unknown member */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mockAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: "vehicle-arrived" | "vehicle-left" | "plate-seen" | "reverse-next-close" | "reset";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Required for `plate-seen` */
                    plate?: string;
                };
            };
        };
        responses: {
            /** @description Applied; returns the resulting state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["State"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Not in mock mode */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
